filter:
    excluded_paths: [vendor/*, exemplos/*, tests/*, libs/External/*]
    paths: [libs/*]

before_commands:
    - "composer install --no-interaction --prefer-source --no-dev"

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit --colors --verbose
    php_analyzer: false
    php_changetracking: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_mess_detector: true
    php_pdepend: true
    php_sim: true

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'php-clover'
